

# irods-provisioner
#
# playbooks/irods-icat.yml - Ansible playbook for configuring an iRODS iCAT
# Author: Ilari Korhonen, KTH Royal Institute of Technology

---

- hosts: all
  become_user: root

  tasks:
    - name: register git repo commit id
      local_action: shell git rev-parse HEAD
      become: no
      register: git_commit_id

    - name: "Build hosts file"
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth1.ipv4.address }} {{item}}" state=present
      when: hostvars[item].ansible_eth1.ipv4.address is defined
      with_items: "{{ groups['all'] }}"

    - name: build provisioner manifest file
      template: src="../templates/irods-provisioner.manifest.j2" dest="/etc/irods-provisioner.manifest" mode=0644 owner=root group=root

    - name: necessary package repositories
      yum: name={{ item }} state=latest
      with_items:
        - epel-release

    - name: necessary management packages
      yum: name={{ item }} state=latest
      with_items:
        - psmisc
        - net-tools
        - htop
        - iotop
        - iftop
        - python-psycopg2
        - httpd
        - php

- hosts: irods-icat
  become_user: root
  
  roles:
    - role: postgres 

    - role: irods-icat

    - role: pgadmin

    - role: emc-metalnx-rmd

- hosts: irods-resource
  become_user: root

  roles:
    - role: irods-resource

    - role: davrods

    - role: emc-metalnx-rmd

- hosts: irods-frontend
  become_user: root

  roles:
    - role: postgres

    - role: emc-metalnx-web