# irods-provisioner
#
# playbooks/irods-cluster.yml - Ansible playbook for configuring a test iRODS cluster
# Author: Ilari Korhonen, KTH Royal Institute of Technology
#
# Copyright (C) 2016-2019 KTH Royal Institute of Technology. All rights reserved.
# See LICENSE file for more information.

---

- hosts: irods
  become_user: root

  tasks:
    - name: register git repo commit id
      local_action: shell git rev-parse HEAD
      become: no
      register: git_commit_id

    - name: "Build hosts file"
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth1.ipv4.address }} {{item}}" state=present
      when: hostvars[item].ansible_eth1.ipv4.address is defined
      with_items: "{{ groups['all'] }}"

    - name: build provisioner manifest file
      template: src="../templates/irods-provisioner.manifest.j2" dest="/etc/irods-provisioner.manifest" mode=0644 owner=root group=root

    - name: necessary package repositories
      yum:
        name:
          - epel-release
        state: latest

    - name: necessary management packages
      yum:
        name:
          - psmisc
          - net-tools
          - htop
          - iotop
          - iftop
          - python-psycopg2
          - httpd
          - php
          - git
        state: latest

- hosts: irods_icat
  become_user: root
  
  roles:
    - role: postgres 

    - role: irods-icat

    # - role: emc-metalnx-rmd

    # - role: irods-nagios

    # - role: irods-logforw

- hosts: irods_resource
  become_user: root

  roles:
    - role: irods-resource

    # - role: davrods

    # - role: emc-metalnx-rmd

    # - role: irods-logforw

- hosts: irods_frontend
  become_user: root

  roles:
    - role: irods-client

    # - role: davrods

    # - role: postgres

    # - role: emc-metalnx-web
