# irods-icat-provisioner
#
# playbooks/irods-icat.yml - Ansible playbook for configuring an iRODS iCAT
# Author: Ilari Korhonen, KTH Royal Institute of Technology

---

- hosts: irods-icat
  become_user: root

  tasks:
    - name: required package repositories
      yum: name={{ item }} state=installed
      with_items:
        - epel-release

    - name: necessary management packages
      yum: name={{ item }} state=latest
      with_items:
        - psmisc
        - net-tools
        - htop
        - iotop
        - iftop
        - python-psycopg2
        - httpd
        - php

  roles:
    - role: postgres 

    - role: irods-icat

    - role: pgpool-II
