# irods-provisioner
#
# roles/pgpool-II/tasks/main.yml - Ansible task for configuring pgpool-II 
# Author: Ilari Korhonen, KTH Royal Institute of Technology
#
# Copyright (C) 2016-2017 KTH Royal Institute of Technology. All rights reserved.
# See LICENSE file for more information.

---

    - name: PostgreSQL 9.4 package repository
      yum: name=http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-redhat94-9.4-3.noarch.rpm state=present

    - name: pgpool-II 3.5 for PostgreSQL 9.4
      yum: name={{ item }} state=latest
      with_items:
        - pgpool-II-94
        - pgpool-II-94-debuginfo
        - pgpool-II-94-extensions

    - name: configure pgpool-II healthcheck database roles on postgres master
      become: yes
      become_user: postgres
      postgresql_user: name={{ item.name }} password={{ item.password }} role_attr_flags={{ item.flags }} encrypted=yes
      when: ha_state == "master"
      with_items:
        - { name: "{{ healthcheck_user }}", password: "{{ healthcheck_passwd }}", flags: "LOGIN" }

    - name: configure pgpool-II healthcheck databases on postgres master
      become: yes
      become_user: postgres
      postgresql_db: name={{ item.name }} owner={{ item.owner }} encoding="UTF-8" template="template1" login_user="postgres"
      when: ha_state == "master"
      with_items:
        - { name: "{{ healthcheck_db }}", owner: "{{ healthcheck_user }}" }

