# irods-provisioner
#
# roles/b2stage-gridftp/tasks/main.yml - Ansible playbook for configuring an EUDAT B2STAGE GridFTP for iRODS
# Author: Ilari Korhonen, KTH Royal Institute of Technology

---

    - name: iRODS packages (version 4.1.10)
      yum: name={{ item }} state=installed
      with_items:
        - ftp://ftp.renci.org/pub/irods/releases/4.1.10/centos7/irods-runtime-4.1.10-centos7-x86_64.rpm
        - ftp://ftp.renci.org/pub/irods/releases/4.1.10/centos7/irods-icommands-4.1.10-centos7-x86_64.rpm
        - ftp://ftp.renci.org/pub/irods/releases/4.1.10/centos7/irods-dev-4.1.10-centos7-x86_64.rpm

    - name: development tools
      yum: name="@Development tools" state=installed

    - name: required packages for building b2stage-gridftp
      yum: name={{ item }} state=latest
      with_items:
        - cmake
        - globus-gridftp-server-progs
        - globus-simple-ca
        - globus-gass-copy-progs
        - globus-common-devel
        - globus-gridftp-server-devel
        - globus-gridmap-callout-error-devel
        - libcurl-devel
        - openssl-devel

    - name: b2stage-gridftp build script
      template: src=../templates/build-b2stage-gridftp.sh.j2 dest=/tmp/build-b2stage-gridftp.sh owner=root group=root mode=0755

    - name: b2stage-gridftp build
      shell: /tmp/build-b2stage-gridftp.sh
      args:
        creates: /opt/iRODS_DSI/libglobus_gridftp_server_iRODS.so
