# irods-provisioner
#
# roles/pgadmin/tasks/main.yml - Ansible playbook for configuring a pgAdmin application
# Author: Ilari Korhonen, KTH Royal Institute of Technology
#
# Copyright (C) 2016-2017 KTH Royal Institute of Technology. All rights reserved.
# See LICENSE file for more information.

---

  - name: PostgreSQL 9.5 package repository
    yum: name=http://yum.postgresql.org/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-3.noarch.rpm state=present

  - name: pgAdmin 4 web application
    yum: name=pgadmin4-v1-web state=latest

  - name: Apache WSGI module
    yum: name=mod_wsgi state=latest

  - name: pgAdmin 4 web reverse proxy config
    template: src=../templates/httpd-pgadmin.conf.j2 dest=/etc/httpd/conf.d/pgadmin.conf owner=root group=root mode=0644

  - name: SElinux to allow httpd to reconnect (reverse proxy)
    command: /usr/sbin/setsebool -P httpd_can_network_connect 1
    when: ansible_selinux['status'] != 'disabled'

  - name: pgAdmin service enabled and started
    service: name=pgadmin4-v1 enabled=yes state=started

  - name: httpd service enabled and started
    service: name=httpd enabled=yes state=started

  - name: add role execution info to irods-provisioner manifest file
    shell: echo "# role pgadmin provisioned successfully at {{ ansible_date_time.iso8601_micro }}" >> /etc/irods-provisioner.manifest
