# irods-provisioner
#
# roles/ipa-server/tasks/main.yml - Ansible playbook for configuring an FreeIPA Authentication/IdM server
# Author: Ilari Korhonen, KTH Royal Institute of Technology
#
# Copyright (C) 2016-2017 KTH Royal Institute of Technology. All rights reserved.
# See LICENSE file for more information.

---

   - name: IPA server packages
     yum: name={{ item }} state=latest
     with_items:
       - ipa-server
       - ipa-server-dns
       
