# irods-provisioner
#
# roles/davrods/tasks/main.yml - Ansible playbook for configuring a DavRods frontend
# Author: Ilari Korhonen, KTH Royal Institute of Technology
#
# Copyright (C) 2016-2017 KTH Royal Institute of Technology. All rights reserved.
# See LICENSE file for more information.

---

    - name: iRODS runtime (version 4.1.11)
      yum: name={{ item }} state=installed
      with_items:
        - ftp://ftp.renci.org/pub/irods/releases/4.1.11/centos7/irods-runtime-4.1.11-centos7-x86_64.rpm

    - name: Apache httpd
      yum: name={{ item }} state=installed
      with_items:
        - httpd
        - httpd-tools
        - mod_ssl

    - name: Davrods version 1.3.0 (release 4.1_1.3.0 for iRODS 4.1.x)
      yum: name=https://github.com/UtrechtUniversity/davrods/releases/download/4.1_1.3.0/davrods-4.1_1.3.0-1.el7.centos.x86_64.rpm state=installed

    - name: SELinux for Davrods - allow httpd to connect to iRODS
      command: "setsebool -P httpd_can_network_connect true"
      when: ansible_selinux['status'] != 'disabled'

    - name: SELinux for Davrods - set correct context for iRODS network plugins
      command: "chcon -t lib_t /var/lib/irods/plugins/network/libtcp.so /var/lib/irods/plugins/network/libssl.so"
      when: ansible_selinux['status'] != 'disabled'

    - name: Davrods configurations
      template: src={{ item.srcfile }} dest={{ item.destfile }} owner=root group=root mode=0644
      with_items:
        - { srcfile: "../templates/davrods-vhost.conf.j2", destfile: "/etc/httpd/conf.d/davrods-vhost.conf" }
        - { srcfile: "../templates/davrods-irods_environment.json.j2", destfile: "/etc/httpd/irods/irods_environment.json" }
      notify: restart httpd

    - name: httpd enabled and started
      systemd: name=httpd enabled=yes state=started

    - name: add role execution info to irods-provisioner manifest file
      shell: echo "# role davrods provisioned successfully at {{ ansible_date_time.iso8601_micro }}" >> /etc/irods-provisioner.manifest