# irods-provisioner
#
# roles/davrods/tasks/main.yml - Ansible playbook for configuring a DavRods frontend
# Author: Ilari Korhonen, KTH Royal Institute of Technology
#
# Copyright (C) 2016-2019 KTH Royal Institute of Technology. All rights reserved.
# See LICENSE file for more information.

---

    - name: iRODS RPM package repository signing key
      shell: "rpm --import https://packages.irods.org/irods-signing-key.asc"
      args:
        warn: false

    - name: iRODS RPM package repository
      get_url:
        url: https://packages.irods.org/renci-irods.yum.repo
        dest: /etc/yum.repos.d/renci-irods.yum.repo

    - name: iRODS runtime (version 4.2.6)
      yum:
        name:
          - irods-runtime-4.2.6
          - irods-icommands-4.2.6
        state: installed

    - name: Apache httpd
      yum:
        name:
          - httpd
          - httpd-tools
          - mod_ssl
        state: installed

    - name: Davrods version 1.4.2 (release for iRODS 4.2.6)
      yum: name=https://github.com/UtrechtUniversity/davrods/releases/download/4.2.6_1.4.2/davrods-4.2.6_1.4.2-1.rpm state=installed

    - name: SELinux for Davrods - allow httpd to connect to iRODS
      command: "setsebool -P httpd_can_network_connect true"
      when: ansible_selinux['status'] != 'disabled'

    - name: SELinux for Davrods - set correct context for iRODS network plugins
      command: "chcon -t lib_t /usr/lib/irods/plugins/network/libtcp_client.so /usr/lib/irods/plugins/network/libssl_client.so"
      when: ansible_selinux['status'] != 'disabled'

    - name: Davrods configurations
      template: src={{ item.srcfile }} dest={{ item.destfile }} owner=root group=root mode=0644
      with_items:
        - { srcfile: "../templates/davrods-vhost.conf.j2", destfile: "/etc/httpd/conf.d/davrods-vhost.conf" }
        - { srcfile: "../templates/davrods-irods_environment.json.j2", destfile: "/etc/httpd/irods/irods_environment.json" }
      notify: restart httpd

    - name: Davrods anonymous access virtual host
      template: src="../templates/davrods-anonymous-vhost.conf.j2" dest="/etc/httpd/conf.d/davrods-anonymous-vhost.conf"
      when: davrods_anon_vhost_enable == true

    - name: httpd enabled and started
      systemd: name=httpd enabled=yes state=started

    - name: add role execution info to irods-provisioner manifest file
      shell: echo "# role davrods provisioned successfully at {{ ansible_date_time.iso8601_micro }}" >> /etc/irods-provisioner.manifest
