# irods-provisioner
#
# roles/irods-icat/tasks/main.yml - Ansible playbook for configuring an iRODS iCAT
# Author: Ilari Korhonen, KTH Royal Institute of Technology
#
# Copyright (C) 2016-2017 KTH Royal Institute of Technology. All rights reserved.
# See LICENSE file for more information.

---
    - name: required base package repositories
      yum:
        name:
          - epel-release
        state: installed

    # - name: Python pexpect remove stock package
    #   yum: name=pexpect state=absent

    # - name: Python pip install 
    #   yum: name=python-pip state=latest

    # - name: Python pexpect install from pip
    #   pip:
    #     name: pexpect

    - name: iRODS RPM package repository signing key
      shell: "rpm --import https://packages.irods.org/irods-signing-key.asc"

    - name: iRODS RPM package repository
      get_url:
        url: https://packages.irods.org/renci-irods.yum.repo
        dest: /etc/yum.repos.d/renci-irods.yum.repo

    - name: iRODS version 4.2.x latest
      yum:
        name:
          - unixODBC
          - irods-runtime
          - irods-server
          - irods-database-plugin-postgres
        state: installed

    - name: configure database roles on postgres master
      become: yes
      become_user: postgres
      postgresql_user: name={{ item.name }} password={{ item.password }} role_attr_flags={{ item.flags }} encrypted=yes
      when: ha_state == "master"
      with_items:
        - { name: "{{ icat_db_user }}", password: "{{ icat_db_passwd }}", flags: "LOGIN" }

    - name: configure databases on postgres master
      become: yes
      become_user: postgres
      postgresql_db: name={{ item.name }} owner={{ item.owner }} encoding="UTF-8" template="template1" login_user="postgres"
      when: ha_state == "master"
      with_items:
        - { name: "{{ icat_db_name }}", owner: "{{ icat_db_user }}" }

    - name: iRODS service group
      group: name={{ __irods_service_group }} state=present

    - name: iRODS service account
      user: name={{ __irods_service_account }} group={{ __irods_service_group }} comment="iRODS Administrator" home={{ __irods_home_dir }}

    # - name: run iRODS server initial setup
    #   expect:
    #     command: python /var/lib/irods/scripts/setup_irods.py
    #     creates: /var/lib/irods/.irods/irods_environment.json
    #     responses:
    #       "*iRODS user*": "{{ irods_service_account }}"
    #       "*iRODS group*": "{{ irods_service_group }}"
    #       "*iRODS server's role*": "1"
    #       "*ODBC driver for postgres*": "PostgreSQL"
    #       "*Database server's hostname or IP address*": "{{ irods_icat_db_host }}"
    #       "*Database server's port*": "{{ irods_icat_db_port }}"
    #       "*Database name*": "{{ irods_icat_db }}"
    #       "*Database username*": "{{ irods_icat_user }}"
    #       "*Please confirm*": "yes"
    #       "*Database password*": "{{ irods_icat_passwd }}"
    #       "*Salt for passwords stored in the database*": "{{ irods_icat_db_salt }}"
    #       "*iRODS server's zone name*": "{{ irods_zone_name }}"
    #       "*iRODS server's port*": "{{ irods_zone_port }}"
    #       "*iRODS port range (begin)*": "{{ irods_xfer_port_min }}"
    #       "*iRODS port range (end)*": "{{ irods_xfer_port_max }}"
    #       "*Control Plane port*": "{{ irods_ctrl_port }}"
    #       "*Schema Validation Base URI (or off)*": "{{ irods_validation_url }}"
    #       "*iRODS server's administrator username*": "{{ irods_admin_user }}"
    #       "*Please confirm*": "yes"
    #       "*iRODS server's zone key*": "{{ irods_zone_key }}"
    #       "*iRODS server's negotiation key (32 characters)*": "{{ irods_negotiation_key }}"
    #       "*Control Plane key (32 characters)*": "{{ irods_ctrl_key }}"
    #       "*iRODS server's administrator password*": "{{ irods_admin_passwd }}"
    #       "*iRODS Vault directory*": "{{ irods_temp_vault_dir }}"

    # - name: write ODBC discovery script (to pin against postgres-9.x  ODBC)
    #   template: src={{ item.srcfile }} dest={{ item.destfile }} owner={{ irods_service_account }} group={{ irods_service_group }} mode=0755
    #   with_items:
    #     - { srcfile: "../templates/irods-find_odbc_postgres.sh.j2", destfile: "{{ irods_home }}/packaging/find_odbc_postgres.sh" } 

    # - name: execute iRODS iCAT initial permissions setup if necessary
    #   shell: "{{ irods_home }}/packaging/setup_irods_service_account.sh < {{ irods_home }}/setup-permissions-answerfile.txt"
    #   args:
    #     creates: "/etc/irods/service_account.config"

    - name: iRODS service account environment directory
      file: path="{{ __irods_home_dir }}/.irods" state=directory owner={{ __irods_service_account }} group={{ __irods_service_group }} mode=0700 

    # - name: execute iRODS iCAT initial setup if necessary on master
    #   shell: "{{ irods_home }}/packaging/setup_irods.sh < {{ irods_home }}/setup-answerfile.txt"
    #   when: ha_state == "master"
    #   args:
    #     creates: "{{ irods_home }}/.irods/irods_environment.json"

    # - name: configure iRODS iCAT
    #   template: src={{ item.srcfile }} dest={{ item.destfile }} owner={{ irods_service_account }} group={{ irods_service_group }} mode=0600
    #   with_items:
    #     - { srcfile: "../templates/irods-dot-odbc.ini.j2", destfile: "{{ irods_home }}/.odbc.ini" }
    #     - { srcfile: "../templates/irods-dot-pgpass.j2", destfile: "{{ irods_home }}/.pgpass" }
    #     - { srcfile: "../../../templates/irods-irods_environment.json.j2", destfile: "{{ irods_home }}/.irods/irods_environment.json" }
    #     - { srcfile: "../templates/irods-service_account.config.j2", destfile: "/etc/irods/service_account.config" }
    #     - { srcfile: "../templates/irods-database_config.json.j2", destfile: "/etc/irods/database_config.json" }
    #     - { srcfile: "../templates/irods-server_config.json.j2", destfile: "/etc/irods/server_config.json" }
    #     - { srcfile: "../../../templates/irods-core-override.re.j2", destfile: "/etc/irods/core-override.re" }
    #   notify: restart irods

    - name: add role execution info to irods-provisioner manifest file
      shell: echo "# role irods-icat provisioned successfully at {{ ansible_date_time.iso8601_micro }}, ha_state={{ ha_state }}" >> /etc/irods-provisioner.manifest
