# irods-provisioner
#
# roles/emc-metalnx-web/tasks/main.yml - Ansible task for configuring EMC MetaLnx web interface 
# Author: Ilari Korhonen, KTH Royal Institute of Technology
#
# Copyright (C) 2016-2017 KTH Royal Institute of Technology. All rights reserved.
# See LICENSE file for more information.

---

  - name: Apache Tomcat
    yum: name=tomcat state=latest

  - name: Apache httpd
    yum:
      name:
        - httpd
        - httpd-tools
        - mod_ssl
      state: installed

  - name: Python pexpect remove stock package
    yum: name=pexpect state=absent

  - name: Python pip install 
    yum: name=python-pip state=latest

  - name: Python pexpect install from pip
    pip:
      name: pexpect

  - selinux: policy=targeted state=permissive
    when: ansible_selinux['status'] != 'disabled'

  - name: EMC MetaLnx web application package (version 1.4.0)
    yum: name=https://bintray.com/metalnx/rpm/download_file?file_path=emc-metalnx-webapp-1.4.0-9.noarch.rpm state=installed

  - name: configure postgres role for metalnx-web
    become: yes
    become_user: postgres
    postgresql_user: name={{ metalnx_db_user }} password={{ metalnx_db_passwd }} role_attr_flags="LOGIN" encrypted=yes
    when: ha_state == "master"

  - name: configure postgres database for metalnx-web
    become: yes
    become_user: postgres
    postgresql_db: name={{ metalnx_db }} owner={{ metalnx_db_user }} encoding="UTF-8" template="template1" login_user="postgres"
    when: ha_state == "master"

  - name: configure apache virtual host for reverse proxy
    template: src=../templates/emc-metalnx-web.conf.j2 dest=/etc/httpd/conf.d/emc-metalnx-web.conf owner=root group=root mode=0644
    notify: restart httpd

  - name: SELinux for emc-metalnx-web - allow httpd to connect to tomcat port 8080
    command: "setsebool -P httpd_can_network_connect true"
    when: ansible_selinux['status'] != 'disabled'

  - name: check for a successful metalnx install
    stat: path=/var/lib/tomcat/webapps/emc-metalnx-web/WEB-INF/classes/irods.environment.properties
    register: metalnx_install

  - name: setup metalnx if not setup already
    expect:
      command: python /opt/emc/setup_metalnx.py
      responses:
        Do you want to use Tomcat located at*: "yes"
        Do you wish to use the current setup instead of creating a new one*: "no"
        Set HTTPS on your Tomcat server*: "no"
        Enter the Metalnx Database type*: "postgresql"
        Enter Metalnx Database Host*: "localhost"
        Enter Metalnx Database Port*: "5432"
        Enter Metalnx Database Name*: "{{ metalnx_db }}"
        Enter Metalnx Database User*: "{{ metalnx_db_user }}"
        Enter Metalnx Database Password*: "{{ metalnx_db_passwd }}"
        Enter iRODS Host*: "{{ metalnx_irods_host }}"
        Enter iRODS Port*: "{{ irods_zone_port }}"
        Enter iRODS Zone*: "{{ irods_zone_name }}"
        Enter Authentication Schema*: "STANDARD"
        Enter iRODS Admin User*: "{{ irods_admin_user }}"
        Enter iRODS Admin Password*: "{{ irods_admin_passwd }}"
        Do you accept these configuration paramaters*: "yes"
    when: metalnx_install.stat.exists == false

  - name: httpd enabled and started
    systemd: name=httpd enabled=yes state=started

  - name: tomcat enabled and started
    systemd: name=tomcat enabled=yes state=started

  - name: add role execution info to irods-provisioner manifest file
    shell: echo "# role emc-metalnx-web provisioned successfully at {{ ansible_date_time.iso8601_micro }}" >> /etc/irods-provisioner.manifest
