# irods-provisioner
#
# roles/emc-metalnx-web/tasks/main.yml - Ansible task for configuring EMC MetaLnx web interface 
# Author: Ilari Korhonen, KTH Royal Institute of Technology
#
# Copyright (C) 2016-2017 KTH Royal Institute of Technology. All rights reserved.
# See LICENSE file for more information.

---

  - name: Apache Tomcat
    yum: name=tomcat state=latest

  - name: EMC MetaLnx web application package (version 1.1.0)
    yum: name=https://bintray.com/metalnx/rpm/download_file?file_path=emc-metalnx-webapp-1.1.0-272.noarch.rpm state=installed

  - name: configure postgres role for metalnx-web
    become: yes
    become_user: postgres
    postgresql_user: name={{ metalnx_db_user }} password={{ metalnx_db_passwd }} role_attr_flags="LOGIN" encrypted=yes
    when: ha_state == "master"

  - name: configure postgres database for metalnx-web
    become: yes
    become_user: postgres
    postgresql_db: name={{ metalnx_db }} owner={{ metalnx_db_user }} encoding="UTF-8" template="template1" login_user="postgres"
    when: ha_state == "master"

  - name: configure apache virtual host for reverse proxy
    template: src=../templates/emc-metalnx-web.conf.j2 dest=/etc/httpd/conf.d/emc-metalnx-web.conf owner=root group=root mode=0644

  - name: SELinux for emc-metalnx-web - allow httpd to connect to tomcat port 8080
    command: "setsebool -P httpd_can_network_connect true"
    when: ansible_selinux['status'] != 'disabled'

  - name: add role execution info to irods-provisioner manifest file
    shell: echo "# role emc-metalnx-web provisioned successfully at {{ ansible_date_time.iso8601_micro }}" >> /etc/irods-provisioner.manifest
