# irods-provisioner
#
# roles/irods-client/tasks/main.yml - Ansible playbook for configuring an iRODS client
# Author: Ilari Korhonen, KTH Royal Institute of Technology
#
# Copyright (C) 2016-2017 KTH Royal Institute of Technology. All rights reserved.
# See LICENSE file for more information.

---

    - name: required package repositories
      yum:
        name:
          - epel-release
        state: installed

    - name: iRODS RPM package repository signing key
      shell: "rpm --import https://packages.irods.org/irods-signing-key.asc"
      args:
        warn: false

    - name: iRODS RPM package repository
      get_url:
        url: https://packages.irods.org/renci-irods.yum.repo
        dest: /etc/yum.repos.d/renci-irods.yum.repo

    - name: iRODS version 4.2.6
      yum:
        name:
          - irods-runtime-4.2.6
          - irods-icommands-4.2.6
        state: installed

    - name: add role execution info to irods-provisioner manifest file
      shell: echo "# role irods-client provisioned successfully at {{ ansible_date_time.iso8601_micro }}" >> /etc/irods-provisioner.manifest
