# irods-provisioner
#
# roles/irods-nagios/tasks/main.yml - Ansible playbook for configuring a Nagios monitoring service for iRODS
# Author: Ilari Korhonen, KTH Royal Institute of Technology
#
# Copyright (C) 2016-2017 KTH Royal Institute of Technology. All rights reserved.
# See LICENSE file for more information.

---

    - name: required package repositories
      yum: name={{ item }} state=installed
      with_items:
        - epel-release

    - name: nagios packages
      yum: name={{ item }} state=latest
      with_items:
        - nagios
        - nagios-common
        - nagios-plugins

    - name: nagios plugins
      yum: name={{ item }} state=latest
      with_items:
        - nagios-plugins-ping
        - nagios-plugins-load
        - nagios-plugins-users
        - nagios-plugins-http
        - nagios-plugins-disk
        - nagios-plugins-ssh
        - nagios-plugins-swap
        - nagios-plugins-procs

    - name: iRODS packages (version 4.1.10)
      yum: name={{ item }} state=installed
      with_items:
        - ftp://ftp.renci.org/pub/irods/releases/4.1.10/centos7/irods-runtime-4.1.10-centos7-x86_64.rpm

    - name: SELinux for nagios - allow httpd to connect to nagios
      command: "setsebool -P httpd_can_network_connect true"
      when: ansible_selinux['status'] != 'disabled'

    - name: SELinux for nagios - permissive mode required!
      selinux: policy=targeted state=permissive
      when: ansible_selinux['status'] != 'disabled'

    - name: nagios service enabled and started
      service: name=nagios enabled=yes state=started

    - name: httpd service enabled and started
      service: name=httpd enabled=yes state=started

    - name: add role execution info to irods-provisioner manifest file
      shell: echo "# role irods-nagios provisioned successfully at {{ ansible_date_time.iso8601_micro }}" >> /etc/irods-provisioner.manifest
